### ISSUE TITLE
Daily Promo Message invisible (white on white)

### ISSUE THREAD

**Issue by jeykodev** [Fiddle-N/material-incognito-dark-theme#7] opened 2018-09-12 04:55 UTC
At first: thanks for supporting the new chrome design, i love it! Keep up the good work!

I've noticed that chromes daily promo message on the bottom of a new empty tab is invisible because white text on a white background is displayed. 

![rep](https://user-images.githubusercontent.com/10532676/45402993-bc759580-b658-11e8-99fe-f79d9299c57b.jpg)

Chrome Version: Version 69.0.3497.92
OS: Windows 10

**Comment by Fiddle-N** [comment] 2018-09-16 08:02
Replicating and fixing this issue is going to be a real pain because messages like that only show up occasionally. The next time I see a Google message I'll see if anything can be done to fix this.

**Comment by mrwm** [comment] 2018-09-17 20:58
This is kinda not on topic with this issue, but is there an API to change the menu and popup colors like the one in the screenshot?

**Comment by Steve2955** [comment] 2018-09-23 08:09
@Fiddle-N I had a promo message this morning and opened the inspector to look at what caused the white color. The following line was responsible for it:

`#prm a, #alp-link, #mv-noti-lks span, #mv-noti-error-lks span { color: rgba(255,255,255,1) !important; }`

I hope this helps you to fix the issue. Keep up the good work.

**Comment by Fiddle-N** [comment] 2018-09-23 17:03
@Steve2955 Thanks for your message today. Without it I would have never noticed that the "NTP message" was now present. Annoyingly, the message does not appear on 1366x768 monitors at 100% zoom, which is currently the laptop that I am using. I had to drop zoom to 90%, and then I saw the message appear.

I've made a small tweak to my theme to fix the issue - I'll be releasing it very soon.

**Comment by Fiddle-N** [comment] 2018-09-23 17:26
Fix has been deployed - your theme should be updating as we speak. @Homer0815, @Steve2955 - do let me know if you see the fix applied correctly. If so I'll be happy to close out this item.

**Comment by jeykodev** [comment] 2018-09-23 17:56
@Fiddle-N yea, it looks good! Thank you so much! I really enjoy this theme.

![1](https://user-images.githubusercontent.com/10532676/45931194-c8235f00-bf6a-11e8-8cda-631bde4b9a87.jpg)

**Comment by Fiddle-N** [comment] 2018-09-23 17:59
@Homer0815 Awesome! In that case, time to close this issue. Thanks to you and @Steve2955 for your help with this.

**Comment by Fiddle-N** [comment] 2018-09-26 22:28
Sorry people, looks like I'm going to have to revert the change. Long story short, fixing the promo text has caused a regression with the text on the chrome://apps page. 

![image](https://user-images.githubusercontent.com/20640528/46112789-ba2c4300-c1e3-11e8-9d83-1ff958274817.png)

**Comment by Steve2955** [comment] 2018-10-15 07:55
I don't know if it's just me, but it seems to be fixed.

![Screenshot](https://user-images.githubusercontent.com/21085384/46936460-be1ee880-d05e-11e8-8e7a-1a477caef622.PNG)

Chrome: Version 69.0.3497.100
OS: Windows 10

**Comment by jeykodev** [comment] 2018-10-15 15:22
@Steve2955 I can confirm that! Weird.

**Comment by Fiddle-N** [comment] 2018-10-18 16:58
Looks like Google fixed the issue without me changing anything. Great!

**Closed as completed by Fiddle-N** 2018-10-18 16:58 UTC
